### ISSUE TITLE
Latest release doesn't include types

### ISSUE THREAD

**Issue by tmcw** [rocicorp/replicache-react#11]
I think the issue is this bit:

https://github.com/rocicorp/replicache-react/commit/1d4671f074f22cffd375d554e755e6407aea82ef#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L35-R36

Previously `index.d.ts` was included: https://unpkg.com/browse/replicache-react@2.0.0/out/ but now it isn't: https://unpkg.com/browse/replicache-react@2.1.0/out/

**Comment by arv** [comment]
Oops. Will fix tomorrow
