### ISSUE TITLE
Allow React 18

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache-react#33]
Our package.json says we do not like React 18.

```
    "react": ">=16.0 <18.0",
    "react-dom": ">=16.0 <18.0",
```

We use `unstable_batchedUpdates` but according to https://blog.saeloun.com/2021/07/22/react-automatic-batching.html that API is still available in 18.

It looks like everything works to me (famous last words)

**Comment by aboodman** [comment]
This has been done.
