### ISSUE TITLE
Inconsistent subscription updates

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-react#4]
When `useSubscription` calls `setState` that immediate re-renders the component. This means that in situations where we have nested components, we can end up rendering inconsistent data and also doing unnecessary renders. Consider:

```
function A(rep) {
  const data = useSubscribe(rep, ...);
  return <B rep={rep} data={data} onClick={() => rep.mutate.foo()}/>;
}

function B(rep, data) {
  const otherData = useSubscribe(rep, ...);
  return ...
}
```
If `rep.mutate.foo()` causes the subscription in `A` to fire, there will be two problems:

1. The data rendered by `A` will be momentarily inconsistent with the data rendered by `B`.  This can cause bad UI or exceptions if developers aren't careful to defend against it.
2. `B` will get rendered twice: once as part of the parent, and again on its own.

Both these have the same underlying problem that `setState()` can often force rendering to happen synchronously. This blog post describes the problem clearly: https://blog.logrocket.com/simplifying-state-management-in-react-apps-with-batched-updates/. See also discussion on Discord: https://discord.com/channels/830183651022471199/880130574629605388/880130592463814737.

It seems we can fix this at least two ways. One by using `unstable_batchedUpdates` as described in the blog post, or another by exposing an API compatible with `useSubscription`: https://github.com/facebook/react/tree/main/packages/use-subscription

It seems like the latter approach might be better for compat with upcoming React changes.

**Comment by aboodman** [comment]
@arv can you prioritize this one. Totally forgot about it since it's in a different repo :-/.

**Comment by arv** [comment]
It seems like we should not depend on `unstable_batchedUpdates` since it only works with `ReactDOM` but I guess that is a problem we could deal with later if there is ever a need to support React Native.

For the `useSubscription`, it seems we could just wrap the react one but I'm not sure what the intended use is? I guess I just need to play with it.
